export const constants = {
    DATABASE_URL:'mongodb://127.0.0.1:27017/bdmsdb',
    DATABASE_CONNECTION: 'DATABASE_CONNECTION',
    PATIENT_MODEL: 'PATIENT_MODEL',
    DOCTOR_MODEL: 'DOCTOR_MODEL',
    APPOINTMENT_MODEL: 'APPOINTMENT_MODEL',
    FEEDBACK_MODEL: 'FEEDBACK_MODEL',
    SLOTS_MODEL: 'SLOTS_MODEL',
    DATE_MODEL:'DATE_MODEL',
    GENDER:{
      MALE:'MALE',
      FEMALE:'FEMALE'
    },
    SPECIALIZATION:{
        PHYSICIAN:'PHYSICIAN',
        SURGEON:'SURGEON',
        ENT:'ENT',
        NEUROLOGIST:'NEUROLOGIST',
        DENTIST:'DENTIST'
    }
  };
  